vich_uploader:
  db_driver: orm

  mappings:
    picture:
      uri_prefix: /client/public/img/uploads
      upload_destination: '%kernel.project_dir%/public/client/public/img/uploads'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    product:
      uri_prefix: /client/public/img/product
      upload_destination: '%kernel.project_dir%/public/client/public/img/product'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
